Repository sahanarao-sps/spring21-sps-30, pull requests merged in 2021-04, with the labels that each got.

#13 Remove contact.html
  src/main/webapp/aboutus.html
  src/main/webapp/contact.html
  src/main/webapp/index.html
  src/main/webapp/translate_sentiment.html
Labels: frontend

#12 Updates sentiment messages to more useful randomized responses.
  src/main/webapp/script.js
Labels: enhancement, middleware

#17 Connects dropdown menu to servlet.
  pom.xml
  src/main/java/com/google/sps/data/WhatsYourSentiment.java
  src/main/java/com/google/sps/servlets/TranslateServlet.java
  src/main/webapp/script.js
  src/main/webapp/translate_sentiment.html
Labels: Servlet, middleware

#16 Creates a visual representation for our sentiment score
  src/main/webapp/script.js
  src/main/webapp/style.css
  src/main/webapp/translate_sentiment.html
Labels: frontend, middleware

#18 Changing website content
  src/main/webapp/aboutus.html
  src/main/webapp/index.html
  src/main/webapp/style.css
  src/main/webapp/translate_sentiment.html
Labels: enhancement, frontend

#19 Favicon!
  src/main/webapp/aboutus.html
  src/main/webapp/android-chrome-192x192.png
  src/main/webapp/android-chrome-512x512.png
  src/main/webapp/apple-touch-icon.png
  src/main/webapp/browserconfig.xml
  src/main/webapp/favicon-16x16.png
  src/main/webapp/favicon-32x32.png
  src/main/webapp/favicon.ico
  src/main/webapp/index.html
  src/main/webapp/mstile-150x150.png
  src/main/webapp/site.webmanifest
  src/main/webapp/translate_sentiment.html
Labels: enhancement, frontend

#20 Fix: Html Encoding Error
  src/main/java/com/google/sps/servlets/TranslateServlet.java
  src/main/webapp/script.js
Labels: Servlet, bug, frontend

#21 Fixes encoding issue in translator servlet
  src/main/java/com/google/sps/servlets/TranslateServlet.java
  src/main/webapp/script.js
Labels: Servlet, bug
